#!/usr/bin/env bash

if [ -z "$1" ]; then echo "ERR command required, 'build', 'run', or 'debug'"; fi
if [ -z "$2" ]; then echo "ERR container name required, eg 'auth-server'"; fi

if [ "$1" == "build" ]; then
	docker build \
		-f ./source/microservices/$2/Dockerfile \
		-t chasemoskal/$2 \
		.
fi

if [ "$1" == "run" ]; then
	docker run \
		--name $2 \
		--mount type=bind,source=$(pwd)/metalback/config,target=/app/metalback/config \
		--network br0 \
		-p 8000:8000 \
		--rm \
		chasemoskal/$2 \
		&
fi

if [ "$1" == "debug" ]; then
	docker run \
		--name $2 \
		--mount type=bind,source=$(pwd)/metalback/config,target=/app/metalback/config \
		--network br0 \
		-p 8000:8000 \
		--rm \
		-it \
		chasemoskal/$2 \
		bash
fi
