#!/usr/bin/env bash

docker run \
	--name auth-server \
	--mount type=bind,source=$(pwd)/metalback/config,target=/app/metalback/config \
	--network br0 \
	-p 8000:8000 \
	--rm \
	chasemoskal/auth-server \
	&
