#!/usr/bin/env bash

declare -a METALKEYS=(
	auth-server
)

for CONFIG in "$@"; do
	rm $CONFIG/*.pem
	for KEY in "${METALKEYS[@]}"; do
		node_modules/redcrypto/generate-keys 2> /dev/null
		mv private.pem $CONFIG/$KEY.private.pem
		mv public.pem $CONFIG/$KEY.public.pem
	done
done
