#!/usr/bin/env bash

# based on instructions from https://stackoverflow.com/questions/61912589/how-can-i-use-github-packages-docker-registry-in-kubernetes-dockerconfigjson

APP_NAMESPACE=$1
GITHUB_USERNAME=$2
GITHUB_READ_PACKAGES_TOKEN=$3

if [[ -z "$APP_NAMESPACE" ]]; then
	echo "arg 1 required: app namespace"
	exit 1
fi

if [[ -z "$GITHUB_USERNAME" ]]; then
	echo "arg 2 required: github username"
	exit 1
fi

if [[ -z "$GITHUB_READ_PACKAGES_TOKEN" ]]; then
	echo "arg 3 required: github read packages token"
	exit 1
fi

AUTH=`echo -n "$GITHUB_USERNAME:$GITHUB_READ_PACKAGES_TOKEN" | base64`

echo "{\"auths\":{\"docker.pkg.github.com\":{\"auth\":\"$AUTH\"}}}" \
	| kubectl -n nce create secret generic dockerconfigjson-github-com \
		--type=kubernetes.io/dockerconfigjson \
		--from-file=.dockerconfigjson=/dev/stdin
